version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - bin
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: './bin < ./.circleci/test.txt > ./.circleci/output.txt'
      - run: 'diff ./.circleci/output.txt ./.circleci/expectedresult.txt'
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test