version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'g++ *.cpp -std=c++11'
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: './a.out < test.txt > output.txt'
      - run: 'diff output.txt expectedresult.txt'
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test