version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: './a.out < ./.circleci/test.txt > ./.circleci/output.txt'
      - run: 'diff ./.circleci/output.txt ./.circleci/expectedresult.txt'
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test