version: 2.1
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: 'g++ *.cpp -std=c++11'
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: './a.out < test.txt > output.txt'
      - run: 'diff output.txt expectedresult.txt'
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test